# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-FileCopyrightText: Jakob Naucke <jnaucke@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

# Inspired by https://github.com/coreos/repo-templates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/tools/virtctl"
      - "/tools/operator-sdk"
    schedule:
      interval: "weekly"
    groups:
      golang:
        patterns:
          - "*"
    ignore:
      # Block newer versions of k8s until bump of OpenShift CI
      - dependency-name: "k8s.io/api"
        versions: [">=0.36"]
      - dependency-name: "k8s.io/apimachinery"
        versions: [">=0.36"]
      - dependency-name: "sigs.k8s.io/controller-runtime"
        versions: [">=0.24"]
      - dependency-name: "sigs.k8s.io/controller-tools"
        versions: [">=0.21"]
      - dependency-name: "github.com/cert-manager/cert-manager"
        versions: [">=1.21"]
      - dependency-name: "github.com/mikefarah/yq"
        versions: [">=4.54"]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      rust:
        patterns:
          - "*"
    ignore:
      - dependency-name: "rand_core"
        # Block newer versions of rand_core, incompatible
        versions: [">=0.7"]
      - dependency-name: "blockdev"
        # Newer versions do not parse lsblk -J output correctly, see
        # https://github.com/wiggels/blockdev/pull/4#issuecomment-5572211474
        versions: [">=0.5"]
      - dependency-name: "kopium"
        # Block newer versions of kopium until we bump to k8s 1.36
        versions: [">=0.23.0"]
