[http_server]
sockets = ["0.0.0.0:8080"]

[admin]
authorization_mode = "AuthenticatedAuthorization"

[admin.authentication.bearer_jwt]
identity_providers = [
  { public_key_uri = "/key/public.pub" }
]

[admin.authorization.regex_acl]
acls = [{ role = "admin", allowed_endpoints = "^/kbs/.+$" }]

[attestation_token]
insecure_header_jwk = true

[attestation_service]
type = "coco_as_builtin"
work_dir = "/opt/trustee"
policy_engine = "opa"

  [attestation_service.attestation_token_broker]
  type = "Ear"
  policy_dir = "/opt/trustee/policies"

  [attestation_service.attestation_token_config]
  duration_min = 5

  [attestation_service.rvps_config]
  type = "BuiltIn"

    [attestation_service.rvps_config.storage]
    type = "LocalJson"
    file_path = "/opt/trustee/reference-values.json"


[[plugins]]
name = "resource"
storage_backend_type = "kvstorage"

[policy_engine]
policy_path = "/opt/trustee/policy.rego"
