[http_server]
sockets = ["0.0.0.0:8080"]

[admin]
authorization_mode = "AuthenticatedAuthorization"

  [admin.authentication.bearer_jwt]
  identity_providers = [
    { public_key_uri = "/opt/trustee/keys/public.pub" }
  ]

  [admin.authorization.regex_acl]
  acls = [{ role = "admin", allowed_endpoints = "^/kbs/.+$" }]

[attestation_token]
insecure_header_jwk = true

[attestation_service]
type = "coco_as_builtin"
timeout = 5

  [attestation_service.attestation_token_broker]
  duration_min = 5

  [attestation_service.rvps_config]
  type = "BuiltIn"

[[plugins]]
name = "resource"
storage_backend_type = "kvstorage"

[storage_backend]
storage_type = "LocalJson"

  [storage_backend.backends.local_json]
  file_dir_path = "/opt/trustee/storage"
